import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {dirname,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {createApp} from '../server.mjs';
const bytes=await readFile(new URL('../.runtime/incidents.json',import.meta.url));
const source=JSON.parse(bytes),rank={low:0,medium:1,high:2,critical:3};
function oracle(p){const values=k=>p.getAll(k);return source.filter(r=>['service','status','severity'].every(k=>!values(k).length||values(k).includes(r[k]))&&(!p.get('q')||[r.id,r.title,r.description].join('\n').toLowerCase().includes(p.get('q').toLowerCase()))&&(!p.get('from')||r.openedAt.substring(0,10)>=p.get('from'))&&(!p.get('to')||r.openedAt.substring(0,10)<=p.get('to'))).sort((a,b)=>{let d=(p.get('sort')==='severity'?rank[a.severity]-rank[b.severity]:Date.parse(a.openedAt)-Date.parse(b.openedAt));if(p.get('direction')!=='asc')d=-d;return d||a.id.localeCompare(b.id);});}
function parseCSV(s){const rows=[];let row=[],value='',quoted=false;for(let i=0;i<s.length;i++){const c=s[i];if(c==='"'){if(quoted&&s[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(value);value='';}else if(c==='\r'&&!quoted&&s[i+1]==='\n'){row.push(value);rows.push(row);row=[];value='';i++;}else value+=c;}assert.equal(quoted,false);assert.equal(value,'');return rows;}
async function start(){const app=await createApp();await new Promise(r=>app.listen(0,'127.0.0.1',r));return {app,url:'http://127.0.0.1:'+app.address().port};}
async function stop(app){app.closeAllConnections();await new Promise(r=>app.close(r));}
test('real HTTP: query semantics, stable ordering, whole-result statistics, details and lossless CSV',async()=>{
 const {app,url}=await start();try{
  const queries=['','q=INC-000001','q=RETRY%2C%20THEN%20CONTINUE','q=slow&service=Billing&service=Accounts&status=open&status=in_progress&severity=high&severity=critical&from=2026-04-10&to=2026-06-01','from=2026-04-01&to=2026-04-01','q=no-such-incident','sort=openedAt&direction=asc','sort=severity&direction=asc','sort=severity&direction=desc','page=2&size=50'];
  for(const query of queries){const p=new URLSearchParams(query),expected=oracle(p),response=await fetch(url+'/api/incidents?'+p);assert.equal(response.status,200);const data=await response.json();const size=Number(p.get('size')||25),page=Number(p.get('page')||1);assert.deepEqual(data.items,expected.slice((page-1)*size,page*size));assert.equal(data.summary.total,expected.length);assert.equal(data.summary.unresolved,expected.filter(r=>r.status!=='resolved').length);assert.equal(data.summary.highSeverity,expected.filter(r=>rank[r.severity]>=2).length);const days=new Map();for(const r of expected)days.set(r.openedAt.slice(0,10),(days.get(r.openedAt.slice(0,10))||0)+1);assert.deepEqual(data.summary.daily,[...days].sort().map(([date,count])=>({date,count})));assert.deepEqual(await (await fetch(url+'/api/incidents?'+p)).json(),data);
   const csvResponse=await fetch(url+'/api/export?'+p);assert.equal(csvResponse.status,200);assert.match(csvResponse.headers.get('content-type'),/text\/csv/);const csv=parseCSV(await csvResponse.text()),fields=Object.keys(source[0]);assert.deepEqual(csv.shift(),fields);assert.deepEqual(csv,expected.map(r=>fields.map(k=>k==='tags'?JSON.stringify(r[k]):String(r[k]??''))));
  }
  for(const row of [source[0],source[1],source[82]])assert.deepEqual(await (await fetch(url+'/api/incidents/'+row.id)).json(),row);
  assert.equal((await fetch(url+'/api/incidents/missing')).status,404);
  for(const q of ['size=30','page=0','service=invalid','sort=team','direction=sideways','from=2026-05-01&to=2026-04-01','from=2026-02-30'])assert.equal((await fetch(url+'/api/incidents?'+q)).status,400,q);
  assert.equal(createHash('sha256').update(await readFile(new URL('../.runtime/incidents.json',import.meta.url))).digest('hex'),createHash('sha256').update(bytes).digest('hex'));
 }finally{await stop(app);}
});
test('sandbox Chromium: main journeys, persistence, keyboard, responsive, real failure and retry',{timeout:120000},async()=>{
 const alias=execFileSync('bash',['-c','command -v qualification-chromium'],{encoding:'utf8'}).trim();const tooling=dirname(alias);
 process.env.PLAYWRIGHT_BROWSERS_PATH=resolve(tooling,'../browsers');await mkdir('.runtime/browser-tmp',{recursive:true});
 const {chromium}=await import('playwright');const {app,url}=await start();let browser;
 try{
  browser=await chromium.launch({channel:'chromium',headless:true,chromiumSandbox:true,env:{...process.env,LD_LIBRARY_PATH:resolve(tooling,'../host-libs/usr/lib/x86_64-linux-gnu'),ALSA_CONFIG_PATH:resolve(tooling,'../host-libs/usr/share/alsa/alsa.conf'),TMPDIR:'.runtime/browser-tmp',TMP:'.runtime/browser-tmp',TEMP:'.runtime/browser-tmp'}});
  const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  let loadingSeen=false;await page.goto(url);await page.waitForFunction(()=>document.querySelector('#total').textContent==='2,400');
  await page.evaluate(()=>{new MutationObserver(()=>{if(document.querySelector('#notice').textContent.includes('Loading'))window.loadingSeen=true;}).observe(document.querySelector('#notice'),{childList:true,subtree:true});});
  assert.equal(await page.locator('#rows tr').count(),25);assert.equal(await page.locator('#search').inputValue(),'');assert.equal(await page.locator('input[type=checkbox]:checked').count(),0);
  await page.screenshot({path:'.runtime/desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Next →',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#page-info').textContent.includes('Page 2'));
  const returnRows=await page.locator('#rows').innerText();await page.locator('.incident-link').first().focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelector('#detail-body dl'));assert.equal(await page.locator('#detail-body dt').count(),8);await page.keyboard.press('Escape');assert.equal(await page.locator('#rows').innerText(),returnRows);assert.equal(await page.locator('.incident-link').first().evaluate(e=>e===document.activeElement),true);
  await page.getByLabel('Search incidents', {exact:true}).fill('RETRY, THEN CONTINUE');await page.waitForFunction(()=>document.querySelector('#total').textContent==='59');await page.waitForFunction(()=>document.querySelector('#page-info').textContent.includes('Page 1'));
  await page.getByLabel('Rows',{exact:true}).selectOption('50');await page.waitForFunction(()=>document.querySelectorAll('#rows tr').length===50);
  await page.getByLabel('Sort',{exact:true}).selectOption('severity:desc');await page.waitForFunction(()=>document.querySelector('#notice').textContent==='');
  loadingSeen=await page.evaluate(()=>window.loadingSeen);assert.equal(loadingSeen,true);await page.getByRole('button',{name:'Save current view',exact:true}).click();await page.getByLabel('View name',{exact:true}).fill('Quoted descriptions');await page.getByRole('button',{name:'Save view',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#save-dialog').open);const viewId=await page.locator('#views').inputValue();
  await page.reload();await page.waitForFunction(()=>document.querySelector('#total').textContent==='2,400');await page.getByLabel('Saved views',{exact:true}).selectOption(viewId);await page.waitForFunction(()=>document.querySelector('#total').textContent==='59');assert.equal(await page.locator('#size').inputValue(),'50');assert.equal(await page.locator('#sort').inputValue(),'severity:desc');assert.equal(await page.locator('#search').inputValue(),'RETRY, THEN CONTINUE');
  const dlPromise=page.waitForEvent('download');await page.getByRole('button',{name:'↓ Export CSV'}).click();const download=await dlPromise;const csv=parseCSV(await readFile(await download.path(),'utf8'));assert.equal(csv.length,60);assert.ok(csv.slice(1).every(r=>r[2].includes('\n')));
  await page.getByRole('button',{name:'Delete view',exact:true}).click();await page.reload();await page.waitForFunction(()=>document.querySelector('#total').textContent==='2,400');assert.equal(await page.locator('#views option').count(),1);
  await page.getByLabel('Accounts',{exact:true}).check();await page.getByLabel('Billing',{exact:true}).check();await page.getByLabel('Open',{exact:true}).check();await page.getByLabel('Critical',{exact:true}).check();await page.getByLabel('From',{exact:true}).fill('2026-04-01');await page.getByLabel('Through',{exact:true}).fill('2026-04-30');await page.getByLabel('Search incidents',{exact:true}).fill('slow');
  const filtered=oracle(new URLSearchParams('service=Accounts&service=Billing&status=open&severity=critical&from=2026-04-01&to=2026-04-30&q=slow'));await page.waitForFunction(total=>document.querySelector('#total').textContent===String(total),filtered.length);assert.ok(await page.locator('#active button').count()>=7);
  await page.getByRole('button',{name:'Save current view',exact:true}).click();await page.getByLabel('View name',{exact:true}).fill('April critical');await page.getByRole('button',{name:'Save view',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#save-dialog').open);const filterView=await page.locator('#views').inputValue();await page.reload();await page.waitForFunction(()=>document.querySelector('#total').textContent==='2,400');await page.locator('#views').selectOption(filterView);await page.waitForFunction(total=>document.querySelector('#total').textContent===String(total),filtered.length);assert.equal(await page.locator('input[type=checkbox]:checked').count(),4);assert.equal(await page.locator('#from').inputValue(),'2026-04-01');
  await page.getByLabel('Search incidents',{exact:true}).fill('zzzz-not-found');await page.waitForFunction(()=>!document.querySelector('#empty').hidden);assert.equal(await page.locator('#total').innerText(),'0');
  await page.getByRole('button',{name:'Clear all',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#total').textContent==='2,400');
  await context.setOffline(true);await page.getByLabel('Search incidents',{exact:true}).fill('INC-000001');await page.getByRole('button',{name:'Retry',exact:true}).waitFor();assert.equal(await page.locator('#search').inputValue(),'INC-000001');await context.setOffline(false);await page.getByRole('button',{name:'Retry',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#total').textContent==='1');
  await page.locator('.incident-link').first().click();await page.waitForFunction(()=>document.querySelector('#detail-body dl'));assert.ok((await page.locator('#detail-body').innerText()).includes('<sample>'));assert.equal(await page.locator('#detail-body sample').count(),0);await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'Clear all',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#total').textContent==='2,400');await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.getByLabel('Search incidents',{exact:true}).focus();assert.equal(await page.locator('#search').evaluate(e=>getComputedStyle(e).outlineStyle),'solid');await page.keyboard.type('INC-000042');await page.waitForFunction(()=>document.querySelector('#total').textContent==='1');await page.locator('.incident-link').first().click();await page.waitForFunction(()=>document.querySelector('#detail-body dl'));await page.keyboard.press('Escape');await page.getByRole('button',{name:'Clear all',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#total').textContent==='2,400');await page.screenshot({path:'.runtime/mobile.png',fullPage:true});
  await page.locator('summary').click();assert.equal(await page.locator('#daily tr').count(),90);assert.deepEqual(errors,[]);
 }finally{if(browser)await browser.close();await stop(app);}
});
